sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: U189G3puKd0d0RzzygSbPTEqVsrAhHxI1k8/6SuGBHsdsL7CxKQq8T1UAjAxOcT7HIMz4gl9Zcc3VGPmxdUlCE62NL8SxONxUdjkhW2oJtGcyJzPDEkDH7aks3NFvPTnNAZmpL2geoBdtLdNEPRENvUOATg5bnzf4T9p9aF52LhJ1NYNMhn7kG2DP0F7A7WZyAEgEiOYtLidyjDsn5e5GsHNyH6/ZSkO6qvi7ie8LbC2+CSwc+rrrNBSsOr8QPz/8WKdv6v2u8wZ6BAXBPf+DbMKp4VRz5PRyP3xZuWS4R5PZARE8cXgBtdHCB8S996903reoIdjFZ7bi/Bu8EC59eECc0MJjun7Ce4tNpZQB0qblwqnau9XdGyMn+W2tIiPMUj/At2phGVvmgCgmerFpsKNTOL2d/TF401EKbEMHboXkxzMthBfH/Ldhok9rY+F+zjvCDdBQnGNTNxW72p2BotheWdfpXqkRJflHLtT34YdHhCfJ376Bu+0lY8E2qrTQk42Y1yW5ojTrxf6tZmWKuMak03NZ7RhHTFAVP0QydTw+6/ZUeU/qEUVnELVKzrEE95LhQWBC/qxQg/MfWz5G1uafYOwCbZoMslby8eFipqRocUOypTguoGGBmNUwTyxPqLwr0JbRIAyWrzUTD2lJI5z2pF+D8MaLx4tkDKnhNo=
