sudo:
  required

dist:
  trusty

addons:
  apt:
    packages:
      - pandoc

language:
  python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  global:
    - TOXENV="py${PYTHON_VERSION//./}"

install:
  - make install
  - pip install coveralls

script:
  - make test

after_success:
  - coveralls

before_deploy:
  - pandoc --version
  - pandoc -f markdown_github -t rst -o README.rst README.md
  - mv README.rst README.md

deploy:
  provider: pypi
  user: roll
  distributions: sdist bdist_wheel
  on:
    tags: true
  password:
    secure: hsJOqF5s4JQSH2Bur7cm8qNBMKdOnsV+oi4YZEO5L85IBDyiYsdhmztTU2SZQBUlXJdQ92bM2Zu1TeDut9becUTz8ZER3xHAdazIa6h5PWcsCsvHMygBNqKb2jLrkFYevO3uvNa/8sUN1cxwbLRiYLNQbx0UmMb7DC3ih0s53Bj6EXPjTrQcy6E1CY+IKxc5NyFoJC+tn93nyjF1BpeVSUgMsEjnDplJgOA2ep+H+BqCFD99FxHOI684yg6PlzU4GablcxrJkkIL0u3XV50h0VC2XurAL1FtHjolBktgy/COp7n6F2gxlVeXuy9FVssSq2Q3NfvSazVmsIEfhs2oe/d1JriVLWfb+gzqvskMf5YheKX+mnWS3SmHXS38oNuySgxLapJqaTEZganHsYKikjszXEfvCDiEdmYYIW6DwLSpk1XOy6TEUI2fQCh1mmFYtgK7sAOkqY9BDlPLKV0WAavDkVDoi9YsN3EJ1nr/k+UvjhRLOJg7vzp/0Cvrh/tZ6e14dWr7dQnMKvyDv8noVFA/UZUOA57h4usEWqKrPdUeSr8B7wHiffFHVYgp/Z/vu0CrbppLaNk3GgXCkTScmkLYfKekWv7f7Lm2W+5xDGucW0DEdpvAfF1bj7VbDtpk/p8fOAs2SQ1ku6lb/iDTZRz+XrS2ojbOqXE8LtdBkrY=
